name: Workspace Images Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      ARTIFACT_REPO_SUB_PATH: ""
    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      # - name: Set image build repo sub path
      #   if: ${{ env.BRANCH_NAME }} != 'master'
      #   run: echo "ARTIFACT_REPO_SUB_PATH=$(echo /${{ env.BRANCH_NAME }})" >> $GITHUB_ENV

      - name: Checkout dazzle
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/dazzle
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - run: go get -v ./...
      - run: go generate -v ./...
      - run: go install
      - name: Checkout workspace-images
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/workspace-images
      - run: sudo su -c "cd /usr; curl -L https://github.com/moby/buildkit/releases/download/v0.9.3/buildkit-v0.9.3.linux-amd64.tar.gz | tar xvz"
      - run: sudo buildkitd --group docker &
      - run: sudo chmod +777 /run/buildkit/buildkitd.sock
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/613222737209/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'workspace-images@prince-tf-experiments.iam.gserviceaccount.com'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 366.0.0
      - run: gcloud auth configure-docker europe-docker.pkg.dev --quiet
      - run: cd dazzle-rewrite && dazzle build europe-docker.pkg.dev/prince-tf-experiments/workspace-images
      - run: cd dazzle-rewrite && dazzle combine europe-docker.pkg.dev/prince-tf-experiments/workspace-images --all
      # - run: cd dazzle-rewrite && dazzle build europe-docker.pkg.dev/prince-tf-experiments/workspace-images${ARTIFACT_REPO_SUB_PATH}
      # - run: cd dazzle-rewrite && dazzle combine europe-docker.pkg.dev/prince-tf-experiments/workspace-images${ARTIFACT_REPO_SUB_PATH} --all
