name: Workspace Images Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      ARTIFACT_REPO_SUB_PATH: ""
      WORKLOAD_IDENTITY_POOL_ID: projects/119379277405/locations/global/workloadIdentityPools/workspace-images-github-actions/providers/workspace-images-gha-provider
      IMAGE_REPO: europe-docker.pkg.dev/workspace-base-images/workspace-base-images/workspace-base-images
      IAM_SERVICE_ACCOUNT: workspace-images-gha-sa@workspace-base-images.iam.gserviceaccount.com

    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)"

      # - name: Set image build repo sub path
      #   if: ${{ env.BRANCH_NAME }} != 'master'
      #   run: echo "ARTIFACT_REPO_SUB_PATH=$(echo /${{ env.BRANCH_NAME }})" >> $GITHUB_ENV

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
        env:
          RUNNER_TEMP: /tmp

      - name: Checkout dazzle
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/dazzle
          path: dazzle-source

      - name: Installing dazzle
        run: |
          cd dazzle-source
          go get ./...
          go generate ./...
          go install

      - name: Checkout workspace-images
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/workspace-images

      - name: Setup buildkit
        run: |
          sudo su -c "cd /usr; curl -L https://github.com/moby/buildkit/releases/download/v0.9.3/buildkit-v0.9.3.linux-amd64.tar.gz | tar xvz"
          sudo buildkitd --oci-worker=true --oci-worker-net=host --debug --group docker &
          sudo su -c "while ! test -S /run/buildkit/buildkitd.sock; do sleep 0.1; done"
          sudo chmod +777 /run/buildkit/buildkitd.sock

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 366.0.0

      # authenticate here, if we authenticate too early, the docker credential file is unavailable
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.3"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{env.WORKLOAD_IDENTITY_POOL_ID}}
          service_account: ${{env.IAM_SERVICE_ACCOUNT}}

      - name: Configuring container registry credentials
        run: gcloud auth configure-docker europe-docker.pkg.dev --quiet

      - name: Start bob proxy
        run: |
          docker rm -f bob-proxy || true
          docker run --name bob-proxy \
            --network host \
            -d -i -t \
            eu.gcr.io/gitpod-core-dev/build/image-builder-mk3/bob:cw-bump-leeway.4 \
            proxy --auth "$(cat ~/.docker/config.json)" --base-ref localhost/invalid ${{env.IMAGE_REPO}}

      - name: Dazzle build
        run: |
          cd dazzle-rewrite
          dazzle build localhost:8080/prince-tf-experiments/dazzle -v

      - name: Dazzle combine
        run: |
          cd dazzle-rewrite
          dazzle combine localhost:8080/prince-tf-experiments/dazzle --all -v
      # - run: cd dazzle-rewrite && dazzle build europe-docker.pkg.dev/prince-tf-experiments/workspace-images${ARTIFACT_REPO_SUB_PATH}
      # - run: cd dazzle-rewrite && dazzle combine europe-docker.pkg.dev/prince-tf-experiments/workspace-images${ARTIFACT_REPO_SUB_PATH} --all
